<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net48</TargetFramework>
    <LangVersion>9.0</LangVersion>
    <Nullable>enable</Nullable>
    <AssemblyName>LocalFix_MiliraFlightNullCheck</AssemblyName>
    <RootNamespace>LocalFix_MiliraFlightNullCheck</RootNamespace>
    <OutputPath>bin\</OutputPath>
    <AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
  </PropertyGroup>

  <PropertyGroup>
    <HarmonyDll Condition="'$(HarmonyDll)'==''">A:\SteamLibrary\steamapps\workshop\content\294100\2009463077\Current\Assemblies\0Harmony.dll</HarmonyDll>
  </PropertyGroup>

  <ItemGroup>
    <Reference Include="Assembly-CSharp">
      <HintPath>A:\SteamLibrary\steamapps\common\RimWorld\RimWorldWin64_Data\Managed\Assembly-CSharp.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="0Harmony">
      <HintPath>$(HarmonyDll)</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="Milira">
      <HintPath>A:\SteamLibrary\steamapps\workshop\content\294100\3256974620\1.6\Assemblies\Milira.dll</HintPath>
      <Private>false</Private>
    </Reference>
  </ItemGroup>
</Project>
